### ISSUE TITLE
"Behind a Proxy" changed behaviour in the new version 0.109.0 (in Uvicorn)

### ISSUE THREAD

**Issue by tiangolo** [tiangolo/fastapi#10978]
### Discussed in https://github.com/tiangolo/fastapi/discussions/10948

This is related to a change in Starlette and Uvicorn, making them more formally follow the ASGI spec, Starlette already does since version 0.35.0 (recently), Uvicorn needs an equivalent change, in process on: https://github.com/encode/uvicorn/pull/2213

More details in the Starlette PR: https://github.com/encode/starlette/pull/2400

<div type='discussions-op-text'>

<sup>Originally posted by **neugeeug** January 12, 2024</sup>
### First Check

- [X] I added a very descriptive title here.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/pydantic/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
uvicorn rest.main:server --host 0.0.0.0 --port 8080 --reload --root-path /proxy

server = FastAPI()

# separate spec at /v1/docs
server.mount("/v1", app_v1)
# separate spec at /v2/docs
server.mount("/v2", app_v2)

#where app_v1, app_v2 is like below
app_v1 = FastAPI(openapi_tags=tags_metadata, title="Pet store")
```

### Description

When I run the uvicorn with the `--root-path` option for the above setup, the server is expecting that I include the defined root path in every request e.g:
 http://localhost:8080/v2/docs is not working (404)
 http://localhost:8080/proxy/v2/docs is working

IN version 0.108.0 It works as described here https://fastapi.tiangolo.com/advanced/behind-a-proxy/

### Operating System

Linux

### FastAPI Version

0.109.0

### Pydantic Version

2.5.3

### Python Version

3.11.5

### Additional Context

_No response_</div>

**Comment by Kludex** [comment]
This was solved in the latest uvicorn: https://github.com/encode/uvicorn/releases/tag/0.26.0

**Comment by insistence** [comment]
Now using uvicorn works well, but the root_path parameter of the FastAPI object still doesn't work

**Comment by insistence** [comment]
> Thanks @insistence, please create a new discussion question with your use case and an example that I can copy-paste to see what is not working, thanks! ☕

Thanks for your quick reply! The new discussion question is #11033

**Comment by RRRajput** [comment]
@insistence this looks like expected behavior because when you add a `root_path` it will be added before ALL the paths (including the statically mounted directories).

**Comment by insistence** [comment]
What confuses me is that the running results of these two pieces of code are inconsistent. This seems to be inconsistent with the description in the official document (https://fastapi.tiangolo.com/advanced/behind-a-proxy/#setting-the-root_path-in-the-fastapi-app). According to the official documentation, the results obtained by setting the root_path parameter to uvicorn or to FastAPI should be consistent.

**Comment by RRRajput** [comment]
Ah Indeed! 

I'm sorry I missed that part. So the problem is that uvicorn's root path is not propagated to fastapi.

**Comment by insistence** [comment]
@tiangolo @Kludex Excuse me, is this a bug?

**Comment by msmitherdc** [comment]
I'm also having an issue with 026 post, see https://github.com/encode/uvicorn/discussions/2244#discussioncomment-8388784

**Comment by Mattiam2** [comment]
Issue correlated with yours.

When I pass the root_path until 0.108 the request url visible in fastapi included the root_path, from 0.109 onwards it doesn't.

Example fastapi 0.108:
![image](https://github.com/tiangolo/fastapi/assets/1143780/18994e62-e3a2-40e0-b029-6f0c472cdfc0)

Example fastapi 0.109.2:
![image](https://github.com/tiangolo/fastapi/assets/1143780/bfb2c5fe-bc90-4c3e-82a0-2a68249660b3)

Also the redirect from trailing slash to without trailing slash doesn't include the root_path anymore, I could fix that by passing through the proxy also the root_path but this doesn't seem to be the correct behaviour.

**Comment by RRRajput** [comment]
@Mattiam2  can you please log an issue for this? Because I think writing here we would not get attention easily since this issue shows up as `Closed`.
