### ISSUE TITLE
The memory usage piles up over the time and leads to OOM

### ISSUE THREAD

**Issue by prav2019** [tiangolo/fastapi#1624]
### First check

* [ ] I added a very descriptive title to this issue.
* [ ] I used the GitHub search to find a similar issue and didn't find it.
* [ ] I searched the FastAPI documentation, with the integrated search.
* [ ] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [ ] I already read and followed all the tutorial in the docs and didn't find an answer.
* [ ] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [ ] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [ ] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [ ] After submitting this, I commit to one of:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Example

Here's a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with my use case:

```Python
from fastapi import FastAPI

app = FastAPI()


@app.get("/")
def read_root():
    return {"Hello": "World"}
```

### Description

* Open the browser and call the endpoint `/`.
* It returns a JSON with `{"Hello": "World"}`.
* But I expected it to return `{"Hello": "Sara"}`.

### Environment

* OS: [e.g. Linux / Windows / macOS]:
* FastAPI Version [e.g. 0.3.0]:

To know the FastAPI version use:

```bash
python -c "import fastapi; print(fastapi.__version__)"
```

* Python version:

To know the Python version use:

```bash
python --version
```

### Additional context

Tracemalloc gave insight on the lines , that are top consumers of memory: (top one seems to be below line in uvicorn)
/usr/local/lib/python3.6/site-packages/uvicorn/main.py:305:
Line:
loop.run_until_complete(self.serve(sockets=sockets))

**Comment by Riki-1mg** [comment]
same issue i faced @prav2019

**Comment by prav2019** [comment]
> same issue i faced @prav2019

Any solution to overcome that @Riki-1mg

**Comment by Riki-1mg** [comment]
No @prav2019, 
do you using aiohttp as http clients in your service ?
https://github.com/tiangolo/fastapi/issues/1623

**Comment by prav2019** [comment]
No @Riki-1mg

**Comment by teymour-aldridge** [comment]
```python
@app.get("/")
def read_root():
  return {"Hello": "World"}
```
Surely the expected behaviour here is to return `{"Hello": "World"}`?

If you want this function to return `{"Hello": "Sara"}` you'd probably need to do something like:

```python
@app.get("/")
def read_root():
  return {"Hello": "Sara"}
```

Further, I can't reproduce your error on my "machine" (it's sitting on a cloud somewhere). You can [see the full details here](https://repl.it/repls/ImpoliteLightblueDemos) but everything looks to be working fine.

I suspect that this is specific to your operating system setup, etc. Would you please provide some more info needed/useful to know in context of how to reproduce the error?

 * How much RAM does your machine have?
 * How much memory is each function calling (ideally include all the debugging output).
This wil look something like the below (example from the Python documentation)
```
[ Top 10 ]
<frozen importlib._bootstrap>:716: size=4855 KiB, count=39328, average=126 B
<frozen importlib._bootstrap>:284: size=521 KiB, count=3199, average=167 B
/usr/lib/python3.4/collections/__init__.py:368: size=244 KiB, count=2315, average=108 B
/usr/lib/python3.4/unittest/case.py:381: size=185 KiB, count=779, average=243 B
/usr/lib/python3.4/unittest/case.py:402: size=154 KiB, count=378, average=416 B
/usr/lib/python3.4/abc.py:133: size=88.7 KiB, count=347, average=262 B
<frozen importlib._bootstrap>:1446: size=70.4 KiB, count=911, average=79 B
<frozen importlib._bootstrap>:1454: size=52.0 KiB, count=25, average=2131 B
<string>:5: size=49.7 KiB, count=148, average=344 B
/usr/lib/python3.4/sysconfig.py:411: size=48.0 KiB, count=1, average=48.0 KiB
```
 * Does your out-of-memory error include a traceback? Please include that if that's the case.

**Comment by prav2019** [comment]
@teymour-aldridge : here is the debug statistics:
Memory Statistics
Top 10 Files
/usr/local/lib/python3.6/site-packages/uvicorn/main.py:305: size=1652 KiB (+1499 KiB), count=4597 (+4172), average=368 B KB

/usr/local/lib/python3.6/site-packages/starlette/applications.py:136: size=1288 KiB (+1173 KiB), count=2290 (+2086), average=576 B KB

/usr/local/lib/python3.6/threading.py:347: size=943 KiB (+854 KiB), count=1836 (+1657), average=526 B KB

/usr/local/lib/python3.6/queue.py:145: size=919 KiB (+835 KiB), count=1783 (+1619), average=528 B KB

/usr/local/lib/python3.6/asyncio/locks.py:233: size=885 KiB (+807 KiB), count=9633 (+8771), average=94 B KB

/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py:82: size=788 KiB (+717 KiB), count=6876 (+6264), average=117 B KB

/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py:77: size=751 KiB (+684 KiB), count=2289 (+2086), average=336 B KB

/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py:146: size=725 KiB (+662 KiB), count=15984 (+14611), average=46 B KB

/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/result.py:376: size=657 KiB (+590 KiB), count=10490 (+9426), average=64 B KB

/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py:285: size=609 KiB (+555 KiB), count=4589 (+4183), average=136 B KB

Scanned Lines that consumes more memory
uvicorn/main.py

loop.run_until_complete(self.serve(sockets=sockets))
starlette/applications.py

scope["app"] = self
python3.6/threading.py

waiters_to_notify = _deque(_islice(all_waiters, n))
python3.6/queue.py

self.not_empty.notify()
asyncio/locks.py

self._waiters = collections.deque()
http/httptools_impl.py

self.parser = httptools.HttpRequestParser(self)
http/httptools_impl.py

self.config = config
http/httptools_impl.py

self.parser.feed_data(data)
engine/result.py

for obj_elem in elem[4]
http/httptools_impl.py

self.timeout_keep_alive, self.timeout_keep_alive_handler

**Comment by prav2019** [comment]
@teymour-aldridge the above grows and cause OOM after a while

**Comment by teymour-aldridge** [comment]
@prav2019 I can't reproduce the bug on either my machine or on a cloud-hosted linux container; this leads me to believe that the problem is in the way that your machine/environment setup.

In the issue template, it asks for the following fields – would you mind filling them in?

    OS: [e.g. Linux / Windows / macOS]:
    FastAPI Version [e.g. 0.3.0]:

Also, there's a "checklist" at the top of the issue which you should fill out!

**Comment by prav2019** [comment]
@teymour-aldridge , this usually happens when there are some traffic over a period of time. Usually this is happening in our prod environment.
OS: using docker image: python 3.6 [so debian ] **Linux 
FastAPI version: fastapi[all]==0.20.0

**Comment by prav2019** [comment]
@teymour-aldridge , current status:
**Top 10 Files**
/usr/local/lib/python3.6/site-packages/uvicorn/main.py:305: size=3650 KiB (+1922 KiB), count=10158 (+5349), average=368 B KB

/usr/local/lib/python3.6/site-packages/starlette/applications.py:136: size=2851 KiB (+1504 KiB), count=5069 (+2673), average=576 B KB

/usr/local/lib/python3.6/threading.py:347: size=2104 KiB (+1110 KiB), count=4083 (+2155), average=528 B KB

/usr/local/lib/python3.6/queue.py:145: size=2049 KiB (+1087 KiB), count=3974 (+2109), average=528 B KB

/usr/local/lib/python3.6/asyncio/locks.py:233: size=1948 KiB (+1017 KiB), count=21295 (+11208), average=94 B KB

/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py:82: size=1744 KiB (+920 KiB), count=15226 (+8037), average=117 B KB

/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py:77: size=1663 KiB (+877 KiB), count=5068 (+2673), average=336 B KB

/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py:146: size=1598 KiB (+839 KiB), count=35181 (+18488), average=47 B KB

/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py:285: size=1349 KiB (+712 KiB), count=10163 (+5364), average=136 B KB

/usr/local/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py:216: size=1288 KiB (+676 KiB), count=30112 (+15818), average=44 B KB

**Comment by teymour-aldridge** [comment]
0.20.0 is a somewhat old version of FastAPI, what happens if you use the latest release instead?

**Comment by prav2019** [comment]
@teymour-aldridge haven't tried with latest version ? but i like to give it a shot, if there were any memory fix done with the versions after 0.20.0

**Comment by prav2019** [comment]
@teymour-aldridge updated to latest version, will report back, once I see the result, Thanks

**Comment by prav2019** [comment]
@teymour-aldridge I checked on our staging, after updating to latest versions [fast api and uvicorn], the memory issue still exists

**Comment by prav2019** [comment]
@teymour-aldridge can this one work, i saw this uvicorn documentation:
**--limit-max-requests <int> - Maximum number of requests to service before terminating the process. Useful when running together with a process manager, for preventing memory leaks from impacting long-running processes.**

**Comment by teymour-aldridge** [comment]
@prav2019 I don't know, it might do. How many requests are you handling and how many machines do you have?

**Comment by prav2019** [comment]
@teymour-aldridge or trying to add gunicorn!!!

**Comment by curtiscook** [comment]
im running into the same issue - memory usage slowly builds over time, runnign on gunicorn with 4 uvicorn workers

**Comment by erikreppel** [comment]
+1, seeing the same issue
```
fastapi==0.55.1
uvicorn==0.11.5
gunicorn==19.10.0
```
Gunicorn + uvicorn worker class

**Comment by curtiscook** [comment]
Reading through the uvicorn code.. adding the max-requests effectively just restarts the server as soon as you hit some arbitrary number of requests? 

https://github.com/encode/uvicorn/blob/e77e59612ecae4ac10f9be18f18c47432be7909a/uvicorn/main.py#L537-L539

I can't find any good documentation on what this number should be either 500? 1000? 10k? 100k?

If anyone has any experience/advice here, I'm all ears

**Comment by prav2019** [comment]
@curtiscook The max-requests restart the service completely, we need to configure workers to keep one running always, when we restart another, was able solve memory issue, but got into one more, now sometimes get multiple requests to workers with same data and each worker creates new entry into database.

**Comment by drissg1** [comment]
@prav2019  So what exactly solved your OOM issue, was it setting the max-requests?

**Comment by curtiscook** [comment]
Hi, 

I actually have not solved my memory leak issue but it's small enough to not be a huge concern. I'm also seeing the memory leak in other async processes so it might be an issue with long running event loops in async python? 

> @curtiscook The max-requests restarts the service completely, we need to configure workers to keep one running always, when we restart another, was able to solve memory issue, but got into one more, now sometimes I get multiple requests to workers with same data and each worker creates new entry into database.

That's what I thought it might do. Not really a great solution then :(

**Comment by teymour-aldridge** [comment]
I would have thought it would be pretty tricky to have a memory leak in Python. Perhaps an underlying issue in the interpreter (C is very good for memory leaks :D) or a C extension module?

Anyway this has peaked my interest, so I'll try and investigate a little to see what's causing the problem.

Is this only happening in Docker containers, or can it be reproduced across a number of devices? I'm not experiencing this issue on my machine, having left a FastAPI process running for a few days (nothing unusual happened).

It's generally a good move to use ephemeral (short-lived) processes to run applications and regularly recycle them in order to reduce the risk/impact a memory leak (which tend to build up over time) can have.

**Comment by curtiscook** [comment]
I haven't tested outside of docker containers/ heroku docker containers

**Comment by teymour-aldridge** [comment]
Ah. I'll try and do some profiling. Unfortunately my time is pretty scarce these days with the number of different projects I'm working on but fingers crossed.

**Comment by binbinah** [comment]
+1

![image](https://user-images.githubusercontent.com/5344741/90848806-58a98a80-e3a0-11ea-9053-538dfb4548f9.png)

```
python 3.6
fastapi==0.60.1
uvicorn==0.11.3
```
uvicorn main:app --host 0.0.0.0 --port 8101 --workers 4    
docker：2 core 2GB memory，CentOS Linux release 7.8.2003 (Core)

client call the function below per minute, and server memory usage slowly builds over time.

```
...
from fastapi import BackgroundTasks
...

@router.get('/tsp/crontab')
def tsp_crontab_schedule(topic: schemas.AgentPushParamsEnum,
                         background_tasks: BackgroundTasks,
                         api_key: str = Header(...)):
    if topic == topic.schedule_per_minute:
        background_tasks.add_task(crontab.schedule_per_minute)
```

**Comment by binbinah** [comment]
![image](https://user-images.githubusercontent.com/5344741/90853608-366a3980-e3ad-11ea-9ec1-9fe8a75d0cc6.png)

**Comment by prav2019** [comment]
> @prav2019 So what exactly solved your OOM issue, was it setting the max-requests?

I restarts will avoid OOM, but I am facing lot of concurrency issues, also have become difficult to trace logs

**Comment by prav2019** [comment]
https://github.com/tiangolo/fastapi/issues/1624#issuecomment-676517603 . The max request fixed OOM, as it restarts server, but it opened to lot of concurrency issues.

**Comment by prav2019** [comment]
did replacing def with async def helped, because I tried long back it didn't!!!!!

**Comment by curtiscook** [comment]
> update:
> 
> I add `async` before `def` and it worked
> refer： [#596 (comment)](https://github.com/tiangolo/fastapi/issues/596#issuecomment-647704509)
> 
> ```
> @router.get('/tsp/crontab')
> def tsp_crontab_schedule(topic: schemas.AgentPushParamsEnum..)
>     pass
> ```
> 
> to
> 
> ```
> @router.get('/tsp/crontab')
> async def tsp_crontab_schedule(topic: schemas.AgentPushParamsEnum..)
>     pass
> ```

either way, you shouldn't have expanding memory. running the route in def is supported and meant to process requests in a new threadpool?

> did replacing def with async def helped, because I tried long back it didn't!!!!!

I've always been running async

**Comment by AdolfVonKleist** [comment]
I am running this in docker with:

- `python==3.8.6`
- `fastapi==0.61.1`
- `uvicorn==0.11.8`

and I am seeing the same issue for some time.  If I understand this thread, it seems that the recommendation is to restart the uvicorn worker(s) periodically, and never run uvicorn alone without a process manager.  I guess it also better to transfer attention to uvicorn?

**Comment by ycd** [comment]
Related to #596, that issue already contains a lot of workarounds and information, please follow the updates over there.

**Comment by curtiscook** [comment]
> Related to #596, that issue already contains a lot of workarounds and information, please follow the updates over there.

It looks like #596 is due to using def instead of async def ? Ive seen this with async def

**Comment by ycd** [comment]
@curtiscook no my point was there are already a lot of workarounds, keeping them in one place would be a better choice for future references, and the developers who face the same problem in the future, can search for a solution in one place that fits their case. 

Even if the most answer is about using `async def ` instead of `def`. The title and the context is very clear actually, Because the issue wasn't about using `def` instead of `async def` in our case. My colleague opened that issue more than one year ago and we're no longer facing memory problems, we're not using `async def` either.

**Comment by delijati** [comment]
run into the same error `def` -> memory leak `async def` -> no memory leak thanks @curtiscook

**Comment by lmssdd** [comment]
Same issue here. Does anybody found a good workaround in the meantime?

**Comment by ycd** [comment]
What version of Python are you using @lmssdd ?

**Comment by lmssdd** [comment]
> What version of Python are you using @lmssdd ?

@ycd it's 3.8.5, running on a DigitalOcean droplet.
it's on gunicorn with Uvicorn workers.

**Comment by talolard** [comment]
> run into the same error `def` -> memory leak `async def` -> no memory leak thanks @curtiscook

Confirming this worked for me. 
Oddly only had the proble on ec2 (deep learning AMI,CPU only). Running on my local machine worked fine

**Comment by imw** [comment]
Python Version: 3.8.9
FastAPI Version: 0.67.0
Environment: Linux 5.12.7 x86_64

We are able to consistently produce a memory leak by using a synchronous Depends:
```
from fastapi import FastAPI, Body, Depends
import typing
import requests

app = FastAPI()

def req() -> bool: 
    r = requests.get("https://google.com")
    return True

@app.post("/")
def root(payload: list = Body(...), got: bool = Depends(req)):
    return payload
```

This is resolved by switch both endpoint and depends to `async def`. This took us a while to hunt down. At first we also thought it only occurred on EC2, but that's because we were disabling our authentication routines for local testing, which is where the issue was located. For those struggling here: check your depends, if you've got them.

**Comment by curtiscook** [comment]
> Python Version: 3.8.9
> FastAPI Version: 0.67.0
> Environment: Linux 5.12.7 x86_64
> 
> We are able to consistently produce a memory leak by using a synchronous Depends:
> 
> ```
> from fastapi import FastAPI, Body, Depends
> import typing
> import requests
> 
> app = FastAPI()
> 
> def req() -> bool: 
>     r = requests.get("https://google.com")
>     return True
> 
> @app.post("/")
> def root(payload: list = Body(...), got: bool = Depends(req)):
>     return payload
> ```
> 
> This is resolved by switching both endpoint and depends to `async def`. This took us a while to hunt down. At first we also thought it only occurred on EC2, but that's because we were disabling our authentication routines for local testing, which is where the issue was located. For those struggling here: check your depends, if you've got them.

I think this might be my issue as well (although I've been ignoring it for awhile. My endpoint is async, but my depends is sync.

**Comment by Daggy1234** [comment]
I'm also having ghastly memory issues. 
<img width="435" alt="image" src="https://user-images.githubusercontent.com/60603110/128873654-198799ad-07ad-4075-ab9b-810cdad1f39d.png">

my code is fully open source, so feel free to peek: https://github.com/daggy1234/dagpi-image

**Comment by munjalpatel** [comment]
> run into the same error `def` -> memory leak `async def` -> no memory leak thanks @curtiscook

@delijati @curtiscook is the fix literally changing `def fn_name` to `async def fn_name`?

In our case, we obviously async functions whenever we are doing something asynchronously such as calling a REST or GraphQL endpoint, etc.

However, we also have a ton of methods where nothing async is happening.
Do you suggest turning them into `async` as well *without* no *await* in them?

What about the class constructors (`def __init__`)?

**Comment by delijati** [comment]
@munjalpatel [1] there you see that every route that is not async will be executed in a separate thread ... the problem is that it used to use by default a thread pool and this uses up to `min(32, os.cpu_count() + 4)` workers [2] so i assume that on some python version this workers are not reused or released and you end up increasing memory. I wrote a litte test app demonstrate that. [3] 

The implementation `run_in_threadpool` from [1] is coming from starlette 0.14.2 [4] (fastapi pinned to that version). but they changed there code to `anyio` [5]. I just looked briefly into the anyio code but to me it looks like an update to the new starlette ,anyio version could fix that memory problem. But :man_shrugging: if fastapi will update to the new starlette.

[1] https://github.com/tiangolo/fastapi/blob/master/fastapi/routing.py#L144
[2] https://docs.python.org/3/library/concurrent.futures.html#threadpoolexecutor
[3] https://github.com/tiangolo/fastapi/issues/596#issuecomment-734880855
[4] https://github.com/encode/starlette/blob/0.14.2/starlette/concurrency.py#L27
[5] https://github.com/encode/starlette/blob/master/starlette/concurrency.py#L27

**Comment by munjalpatel** [comment]
Thanks @delijati I'll do some experiments with this as well.
We are using `amd64/pypy:3.7` if that matters.

This is a serious issue for us where every `FastAPI` based pods eventually get OOMed and restarted.

![image](https://user-images.githubusercontent.com/2717686/129217087-d5dea73c-3654-4b19-b46c-e5318fe06425.png)

**Comment by munjalpatel** [comment]
Just verified that for us moving functions to `async` still doesn't app.

For example, this pod has almost all methods as `async` and we still see memory creeping.

![image](https://user-images.githubusercontent.com/2717686/129217543-c1666b2c-b0bd-458a-b9d0-1eb53c829da1.png)

**Comment by codejunction** [comment]
I'm creating a ThreadPoolExecutor in the background job. after execution completion, the threads do get closed with all futures resolved, the process creating the threads just doesn't close and takes up memory

**Comment by maitham** [comment]
Yea it's getting pretty unusable for us too, due to this issue. It's pretty major and whilst we love Fast API, we're debating whether to switch to a different framework to fix this issue.

**Comment by curtiscook** [comment]
FWIW -- you may have luck switching to hypercorn workers (plus you get http/2)

**Comment by sostholmwork** [comment]
We're also experiencing this issue using Starlette <=0.14.2. We've got a few services using the same setup of docker + Starlette and they all eventually go OOM and killed,

**Comment by evalkaz** [comment]
I am also getting memory issues. Tested out FastAPI + hypercorn but the issue remains.

**Comment by prav2019** [comment]
I have implemented hacky way to restart workers, but I don't think it is a good idea to restart services. Waiting for a solution, so that I can remove restart logic and not to care about this weird OOM issue.

**Comment by lamnguyenx** [comment]
In my case:
- I tried multiple memory profiling tools but they didn't work well with such complex application like FastAPI
- tracemalloc() did partly work but the it didn't report the memory correctly. I guess it had trouble working with asyncio and ThreadPoolExecutor.

Finally, I was able to track down the memory leak by simply **commenting block by block** in my code. Turns out, it was due to this snippet at the top of `main.py`:

```
from starlette.exceptions import HTTPException as StarletteHTTPException
from fastapi.responses import PlainTextResponse
@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request, exc):
    return PlainTextResponse(str(exc.detail), status_code=exc.status_code)
```

By **converting that async function to normal function**. The memory stopped leaking (I used locust to spawn 4000 users uploading an audio file of 20 seconds):

```
from starlette.exceptions import HTTPException as StarletteHTTPException
from fastapi.responses import PlainTextResponse
@app.exception_handler(StarletteHTTPException)
def http_exception_handler(request, exc):
    return PlainTextResponse(str(exc.detail), status_code=exc.status_code)
```

**Comment by yangxuhui** [comment]
@lamnguyenx By converting async `http_exception_handler`  function to normal function, the issue remains. 
![image](https://user-images.githubusercontent.com/9004682/147723729-3fc40b18-afad-44e3-ba43-b1d28dcc18c1.png)

**Comment by lamnguyenx** [comment]
> @lamnguyenx By converting async `http_exception_handler`  function to normal function, the issue remains. 
> 
> ![image](https://user-images.githubusercontent.com/9004682/147723729-3fc40b18-afad-44e3-ba43-b1d28dcc18c1.png)
> 
> 

Could you try removing the custom http exception handling for now?

**Comment by samjacobclift** [comment]
I did encounter this issue last week, the root cause looked to be mismatched Pydantic types. For instance we had a `int` defined in a response model but was actually a float when returned from our database. We also had an `int` that was also a `str`. Cleaning up the types solved the issue for use. This was a high traffic endpoint of < 100rps

I'm not sure the root cause but I suspect that the errors are caught in and recored in Pydantic somewhere, I suspect [here](https://github.com/samuelcolvin/pydantic/blob/e9327b85fc5f3e14ae3efdd142c68478f6899dc9/pydantic/error_wrappers.py) as FastAPI validates returned responses [here](https://github.com/tiangolo/fastapi/blob/master/fastapi/routing.py#L127).

**Comment by jacksmith15** [comment]
I'm wondering if the `run_in_threadpool(field.validate, ...)` call [here](https://github.com/tiangolo/fastapi/blob/master/fastapi/routing.py#L129-L131) in combination with [the global EXC_TYPE_CACHE](https://github.com/samuelcolvin/pydantic/blob/e9327b85fc5f3e14ae3efdd142c68478f6899dc9/pydantic/error_wrappers.py#L137) used by Pydantic's validation could be contributing.

**Comment by robertop23** [comment]
Any updates on this?

I'm using:

python = 3.8.2
uvicorn = 0.14.0
fastapi = 0.65.2

I changed all my routes to async and the issue persist. My app starts at 300MB and quickly jumps to 1400 after a couple of requests and rever go back

**Comment by Astral1020** [comment]
I have same issue. pod only have 2G RAM, so the pod restart over and over again.......

**Comment by amyruski** [comment]
Is there any valid workarounds for this? And is this true my a fastapi issue or a uvicorn issue? There are similar issues in both projects but it seems like there is no one concrete answer.

**Comment by nikhilkharade** [comment]
I am also facing a similar issue.
All my api endpoints are defined with async.

One thing I have observed though. When I comment out my background tasks (which mainly consist of Database update queries) a consistent increase in RAM was not observed even after load testing with Locust at 300RPS. 


If it helps the database I am using is Postgres.

**Comment by Apiens** [comment]
Hello guys I and my colleagues had a similar issue and we solved it.
<img width="300" alt="image" src="https://user-images.githubusercontent.com/53146455/161678483-07fd54ee-1b71-4cc5-b80d-7ce5164f8a9c.png">

After profiling we found out the coroutines created by uvicorn did not disappear but remain in the memory (health check request, which basically does nothing could increase the memory usage).
This phenomenon was only observed in the microservices that were using `tiangolo/uvicorn-gunicorn-fastapi:python3.9-slim-2021-10-02` as base image. After changing the Image, the memory did not increased anymore.

 - if you are using `tiangolo/uvicorn-gunicorn-fastapi` as base docker image, try building from python official image. [it worked for us]
 - if it doesn't work, profile your own reason. the script below may help you.

```
# [Memory Leak Profiler]
# REF: https://tech.gadventures.com/hunting-for-memory-leaks-in-asyncio-applications-3614182efaf7

def format_frame(f):
    keys = ["f_code", "f_lineno"]
    return OrderedDict([(k, str(getattr(f, k))) for k in keys])

def show_coro(c):
    data = OrderedDict(
        [
            ("txt", str(c)),
            ("type", str(type(c))),
            ("done", c.done()),
            ("cancelled", False),
            ("stack", None),
            ("exception", None),
        ]
    )
    if not c.done():
        data["stack"] = [format_frame(x) for x in c.get_stack()]
    else:
        if c.cancelled():
            data["cancelled"] = True
        else:
            data["exception"] = str(c.exception())
    return data

async def trace_top20_mallocs(sleep_time = 300):
    """
    See https://docs.python.org/ko/3/library/tracemalloc.html
    """
    # has_snap_shot_before = False

    initial_snapshot = (
        tracemalloc.take_snapshot()
    )  # copy.deepcopy(tracemalloc.take_snapshot())
    while True:
        if tracemalloc.is_tracing():
            snapshot = tracemalloc.take_snapshot()
            top_stats = snapshot.compare_to(
                initial_snapshot, "lineno"
            )  # snapshot.statistics("lineno")
            print(f"[ TOP 20 ] diff {datetime.now()}")
            traces = [str(x) for x in top_stats[:20]]
            for t in traces:
                print(t)
            await asyncio.sleep(sleep_time)


async def show_all_unfinished_coroutine_status(sleep_time=200):
    cnt = 0
    while True:
        await asyncio.sleep(sleep_time)
        tasks = asyncio.all_tasks()
        if len(tasks) != cnt:

            for task in tasks:
                formatted = show_coro(task)
                print(json.dumps(formatted, indent=2))
            cnt = len(tasks)
        print(len(tasks))


loop = asyncio.get_running_loop()
asyncio.ensure_future(trace_top20_mallocs(), loop=loop)
asyncio.ensure_future(show_all_unfinished_coroutine_status(), loop=loop)
```

**Comment by curtiscook** [comment]
> Hello guys I and my colleagues had a similar issue and we solved it. <img alt="image" width="300" src="https://user-images.githubusercontent.com/53146455/161678483-07fd54ee-1b71-4cc5-b80d-7ce5164f8a9c.png">
> 
> After profiling we found out the coroutines created by uvicorn did not disappear but remain in the memory (health check request, which basically does nothing could increase the memory usage). This phenomenon was only observed in the microservices that were using `tiangolo/uvicorn-gunicorn-fastapi:python3.9-slim-2021-10-02` as base image. After changing the Image, the memory did not increased anymore.
> 
> * if you are using `tiangolo/uvicorn-gunicorn-fastapi` as base docker image, try building from python official image. [it worked for us]
> * if it doesn't work, profile your own reason. the script below may help you.
> 
> ```
> # [Memory Leak Profiler]
> # REF: https://tech.gadventures.com/hunting-for-memory-leaks-in-asyncio-applications-3614182efaf7
> 
> def format_frame(f):
>     keys = ["f_code", "f_lineno"]
>     return OrderedDict([(k, str(getattr(f, k))) for k in keys])
> 
> def show_coro(c):
>     data = OrderedDict(
>         [
>             ("txt", str(c)),
>             ("type", str(type(c))),
>             ("done", c.done()),
>             ("cancelled", False),
>             ("stack", None),
>             ("exception", None),
>         ]
>     )
>     if not c.done():
>         data["stack"] = [format_frame(x) for x in c.get_stack()]
>     else:
>         if c.cancelled():
>             data["cancelled"] = True
>         else:
>             data["exception"] = str(c.exception())
>     return data
> 
> async def trace_top20_mallocs(sleep_time = 300):
>     """
>     See https://docs.python.org/ko/3/library/tracemalloc.html
>     """
>     # has_snap_shot_before = False
> 
>     initial_snapshot = (
>         tracemalloc.take_snapshot()
>     )  # copy.deepcopy(tracemalloc.take_snapshot())
>     while True:
>         if tracemalloc.is_tracing():
>             snapshot = tracemalloc.take_snapshot()
>             top_stats = snapshot.compare_to(
>                 initial_snapshot, "lineno"
>             )  # snapshot.statistics("lineno")
>             print(f"[ TOP 20 ] diff {datetime.now()}")
>             traces = [str(x) for x in top_stats[:20]]
>             for t in traces:
>                 print(t)
>             await asyncio.sleep(sleep_time)
> 
> 
> async def show_all_unfinished_coroutine_status(sleep_time=200):
>     cnt = 0
>     while True:
>         await asyncio.sleep(sleep_time)
>         tasks = asyncio.all_tasks()
>         if len(tasks) != cnt:
> 
>             for task in tasks:
>                 formatted = show_coro(task)
>                 print(json.dumps(formatted, indent=2))
>             cnt = len(tasks)
>         print(len(tasks))
> 
> 
> loop = asyncio.get_running_loop()
> asyncio.ensure_future(trace_top20_mallocs(), loop=loop)
> asyncio.ensure_future(show_all_unfinished_coroutine_status(), loop=loop)
> ```

This is great. I'm 90% sure that the issue you found is the one that I was experiencing. As one of the early posters on this issue, I haven't noticed this issue anymore--but there were a few things that have happened since... Namely:
1. I've been upgrading FastAPI
2. I moved from uvicorn to hypercorn since hypercorn supports HTTP/2

It's possible that I still have a memory leak, but it's not as detrimental as 2 years ago.


Re:

> --max requests 1 --workers 10. This helped me. You can get 10 simultaneous request where each worker will be restarted when request is finished. Thus the memory will be released.

I don't think this is a viable solution since I believe this blocks the event loop and relies on multiprocessing, which skips out on one of the major benefits of the ASGI server (not getting [thread/process]bound with a single worker)


I don't know if @tiangolo has any thoughts? I feel like we're finally closer to being able to close this issue

**Comment by Xcompanygames** [comment]
I'm having a massive leak with tensorflow + inference with dockerized fastapi + uvicorn server. anyone met that?

**Comment by evalkaz** [comment]
While it didn't completely solve memory pile up over time, using `gunicorn_conf.py` attached below made the increase minimal over time.

```python
import os

host = os.getenv("HOST", "0.0.0.0")
port = os.getenv("PORT", "8000")

# Gunicorn config variables
loglevel = os.getenv("LOGLEVEL", "error")
workers = int(os.getenv("WORKERS", "2"))
bind = f"{host}:{port}"
errorlog = "-"
logconfig = "/logging.conf"
```

**Comment by JorgeRuizDev** [comment]
@Xcompanygames Consider Using ONNX instead of TF as it's usually faster and more reliable. 

I'm having a memory leak, but i think is because the inference data stays on memory / gets dupped at some point. 
I'll update later if the issue is not related with the inference process.

**Comment by Bears-Eat-Beets** [comment]
Can confirm I am experiencing the same issue. Using Python 3.10 + FastAPI + Hypercorn[uvloop] with 2 workers.
The FastAPI project is brand new, so there isn't any tech debt that could possibly be the cause.

`
[tool.poetry.dependencies]
python = "^3.9"
celery = "^5.2.3"
neo4j = "^4.4.3"
hypercorn = {extras = ["uvloop"], version = "^0.13.2"}
fastapi = "^0.77.1"
`

The Docker container starts at around 105.8 MiB of RAM usage when fresh.

After running a Locust swarm (40 Users) all hitting an endpoint that returns data ranging from 200KB to 8MB - the RAM usage of the Docker container grows (and sometimes shrinks, but mostly grows) until I get an OOM exception. The endpoint retrieves data from the Neo4J database and closes the driver connection cleanly each time.

I had some success making the function `async def` even though there was nothing to `await` on. But it seems that FastAPI is still holding onto some memory somewhere... caching?

I'm curious why this topic isn't more popular; surely everyone would be experiencing this. Perhaps we all notice it due to our endpoints returning enough data for us to notice the increase in usage, whereas the general user would most times only return a few KB at a time.

**Comment by Atheuz** [comment]
I've also experienced this, I don't really understand what causes it.

**Comment by SarloAkrobata** [comment]
@tiangolo Is there any updates on this? Thank you.

**Comment by JP-Globality** [comment]
I'm also noticing that memory keeps on increasing when hitting my service with 20 virtual users. Am using `gunicorn` + `fastapi` + `uvicorn`.

![image](https://user-images.githubusercontent.com/75979741/172804975-84c4e5f9-3b75-4e57-9363-63f680041217.png)

**Comment by astrojuanlu** [comment]
Many folks are affected by this issue so definitely _something is happening_, but it could as well be that the problem is in the user code and not in fastapi. So I suggest that, to make things easier for the maintainers, if you're affected by this issue

1. Try to give as many details as possible. How is your setup? What versions/Docker images are you using? What Python version, operating system, gunicorn version, etc?
2. Detail in what timeframe does your issue appear - weeks, days, hours? Does making more requests to the server accelerate the issue? Does the issue still appear if zero requests are made?
3. Have a look at [memray](https://github.com/bloomberg/memray) to better understand your program or use [@Apiens method above](https://github.com/tiangolo/fastapi/issues/1624#issuecomment-1088254112). Share your results in [Gist](https://gist.github.com/) or similar platforms.

Memory issues are tricky but without a good reproducer, it will be impossible for the maintainers to declare whether this is still a problem or not, and if it is, to fix it.

**Comment by Lujeni** [comment]
If this can help with debugging, using `pyenv` was able to reproduce the memory leak under python 3.8.X using multiple middlewares.
```
2243 memory blocks: 3820.5 KiB
  File "/home/lujeni/.pyenv/versions/3.8.13/lib/python3.8/asyncio/locks.py", line 257
    self._waiters = collections.deque()
8563 memory blocks: 3725.5 KiB
  File "/home/lujeni/.pyenv/versions/3.8.13/lib/python3.8/asyncio/events.py", line 81
    self._context.run(self._callback, *self._args)
6773 memory blocks: 3470.5 KiB
  File "/home/lujeni/.pyenv/versions/3.8.13/lib/python3.8/asyncio/base_events.py", line 1859
    handle._run()
22091 memory blocks: 2841.9 KiB
  File "/home/lujeni/.pyenv/versions/uep-moulinex-3.8.13/lib/python3.8/site-packages/starlette/middleware/base.py", line 30
    await self.app(scope, request.receive, send_stream.send)
20978 memory blocks: 2390.5 KiB
  File "/home/lujeni/.pyenv/versions/3.8.13/lib/python3.8/asyncio/base_events.py", line 431
    task = tasks.Task(coro, loop=self, name=name)
4381 memory blocks: 2375.4 KiB
  File "/home/lujeni/.pyenv/versions/3.8.13/lib/python3.8/asyncio/base_events.py", line 570
    self._run_once()
[...]
```

Via python `3.9.x` or `3.10.x` there is no issue

**Comment by tranvannhat** [comment]
same issue

**Comment by pkucmus** [comment]
I see the same thing across all my services using different FastApi/Uvicorn/Gunicorn and Sentry SDK versions.
This particular one is running:

- Python 3.10
- starlette 0.17.1
- fastapi 0.75.1
- sentry-sdk 1.5.0 (maybe it's causing issues)
- gunicorn 20.1.0
- uvicorn 0.17.6

And is receiving short-lived requests that trigger longer but relatively short background tasks (not like I made myself a Celery out of it). Another thing I can think of is my ignorance around the subject of database connections where we go something like

```python
engine = create_async_engine(settings.database_dsn)
session_factory = sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)
Session = async_scoped_session(session_factory, scopefunc=current_task)
Base = declarative_base()


@asynccontextmanager
async def get_db():
    session = Session()
    try:
        yield session
        await session.commit()
    except:
        await session.rollback()
        raise
    finally:
        await session.close()
```

and then use `get_db` with a `with` or `Depends(get_gb)` (I'm very unsure how to work with a DB and FastAPI but that's another thing), but when I had this service on sync SQLAlchemy I was running into many issues where the connections were not going back to the connection pool, resulting in timeouts when waiting for a db connection.

Using Gunicorn with the `uvicorn.workers.UvicornWorker` worker, workers set to `4`

Here's the memory usage (the spike on 10/21 is where I increased a replica count and it immediately hogged a lot of memory):
![image](https://user-images.githubusercontent.com/6347418/197353881-8434fec2-f1ac-48d7-b39e-99ceaf66e30d.png)
(green is memory %, red is CPU %)

to put it in traffic context (not that any correlation can be seen):
![image](https://user-images.githubusercontent.com/6347418/197353920-30f4b8b8-2a46-48e0-a9b0-0f38a84472a8.png)

I wanted to limit requests for gunicorn to refresh the workers but I'm getting `Error while closing socket [Errno 9] Bad file descriptor` which seems related to https://github.com/benoitc/gunicorn/issues/1877

Please tell me if I can help i.e. by providing more data.

**Comment by Kludex** [comment]
We solved a memory leak on uvicorn [0.18.3](https://github.com/encode/uvicorn/releases/tag/0.18.3), and there were some things solved on FastAPI since the mentioned versions.

Can someone confirm this issue is still happening with the latest uvicorn and FastAPI?

**Comment by amchelmer** [comment]
Had an OOM issue whilst running Uvicorn 0.17.2 using tiangolo's pre-built image. The issue hasn't reappeared after switching to a self-built image based on Python 3.10.

**Comment by LLYX** [comment]
> There are 44 participants on this issue, maybe more subscribed. Can we please focus, and not bother people with information that is not relevant?
> 
> If someone can reply my last question, I can proceed from there.

![image](https://user-images.githubusercontent.com/10430633/204930674-655128ec-03c9-4d2c-a826-a6cee5ca1de6.png)

I'm still having this issue, the first part of that (from roughly 85% utilization to 100%) was on FastAPI 0.85.0 and Uvicorn 0.17.6/Gunicorn 20.1.0/Starlette 0.20.4. The first big drop (down to ~65% utilization) was when my autoscaler kicked in from 1 to 4, and the second big drop (down to ~20%) was when I turned off autoscaling and upgraded a single instance from 512MB to 2GB of memory. Alongside the instance upgrade, I also updated FastAPI to 0.87.0, Uvicorn to 0.20.0, and Starlette to 0.21.0, and it seems like my memory usage is still creeping up (from a base usage of ~380MB to currently 515MB, which would've hit 100% memory utilization again if I stayed at the previous instance size).

The instance is hosted by Render, and it does health check requests.

**Comment by Kludex** [comment]
Are you able to share an MRE?

**Comment by evalkaz** [comment]
I upgraded to:
```
fastapi = "^0.88.0"
starlette = "^0.22.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
gunicorn = "^20.1.0"
```
and the issue still persists (you can see a restart when an instance reached 600mb RAM usage):
![image](https://user-images.githubusercontent.com/6222947/204988403-f9ce5f7d-3abb-444e-82af-b7a33a078a06.png)

<details>
<summary>pyproject.toml</summary>

```
[tool.poetry.dependencies]
python = ">=3.11,<3.12"
fastapi = "^0.88.0"
starlette = "^0.22.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
gunicorn = "^20.1.0"
lightgbm = "^3.3.3"
jaeger-client = "^4.8.0"
prometheus-client = "^0.15.0"
scipy = "1.9.3"
```
</details>

**Comment by Kludex** [comment]
Are you able to share a minimal, reproducible, example?

**Comment by lorosanu** [comment]
Would this [simple-api](https://github.com/lorosanu/simple-api) sample help?
* [app.py](https://github.com/lorosanu/simple-api/blob/main/simple_api/app.py)
* [pyproject.toml](https://github.com/lorosanu/simple-api/blob/main/pyproject.toml)
* [Dockerfile](https://github.com/lorosanu/simple-api/blob/main/Dockerfile)

As far as I can tell
- the memory increase is most visible on invalid requests (not exclusively though, but maybe this can point you in the right direction?)
- it is not the fault of pydantic validation
- it is not the fault of uvicorn

**Comment by Kludex** [comment]
> it is not the fault of pydantic validation
> it is not the fault of uvicorn

I don't think the arguments used there are enough to discard those.

Thanks for the MRE. :+1:
