### ISSUE TITLE
[BUG] OpenAPI fails when forcing query params to be body and multiple params in each

### ISSUE THREAD

**Issue by ebanner** [tiangolo/fastapi#284]
**Describe the bug**

The OpenAPI spec for my app breaks with the following error (shown in my web browser).

```
Fetch error
Internal Server Error /openapi.json
```

This only happens when I have endpoints defined in two separate files, each of which force all their arguments to be body parameters via annotating each parameter with `Body(...)` to force them to be body parameters, as opposed to query parameters.

Check this out!

- If the endpoints are defined in the same file, then the problem does not happen.
- If each endpoint only has a single parameter, the problem does not happen.
- If only one endpoint has multiple parameters, then the problem does not happen.

It only happens when both endpoints have *multiple* parameters annotated with `Body(...)`.

**To Reproduce**

1. Create a directory with the following structure.

```
.
├── foo
│   ├── __init__.py
│   ├── bar.py
│   └── baz.py
└── main.py
```

main.py

```python
from fastapi import FastAPI

import foo.bar
import foo.baz

app = FastAPI()

app.get('/v1/compute')(foo.bar.compute)
app.get('/v2/compute')(foo.baz.compute)
```

foo/bar.py

```python
from fastapi import Body

def compute(
        a: int = Body(...),
        b: str = Body(...),
):
    return a + b 
```

foo/baz.py (identical to foo/bar.py)

```python
from fastapi import Body

def compute(
        a: int = Body(...),
        b: str = Body(...),
):
    return a + b
```

2. Run with `uvicorn main:app --reload`
3. Visit `http://localhost:8000/docs`

**Expected behavior**

The OpenAPI page shows without error.

**Screenshots**

![image](https://user-images.githubusercontent.com/2068912/58768563-3e448080-8552-11e9-92b1-cfc1e8040d68.png)

Here's the exception my app produces when I try to visit `http://localhost:8000`.

```
ip-10-8-0-198% % uvicorn run:app --reload
INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO: Started reloader process [77186]
WARNING:root:email-validator not installed, email fields will be treated as str.
To install, run: pip install email-validator
INFO:uvicorn:Started server process [77188]
INFO:uvicorn:Waiting for application startup.
INFO:uvicorn:('127.0.0.1', 54932) - "GET /docs HTTP/1.1" 200
INFO:uvicorn:('127.0.0.1', 54932) - "GET /openapi.json HTTP/1.1" 500
ERROR:uvicorn:Exception in ASGI application
Traceback (most recent call last):
  File "/Users/edwardbanner/.anaconda/lib/python3.6/site-packages/uvicorn/protocols/http/httptools_impl.py", line 368, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/edwardbanner/.anaconda/lib/python3.6/site-packages/uvicorn/middleware/asgi2.py", line 7, in __call__
    await instance(receive, send)
  File "/Users/edwardbanner/.anaconda/lib/python3.6/site-packages/starlette/middleware/errors.py", line 125, in asgi
    raise exc from None
  File "/Users/edwardbanner/.anaconda/lib/python3.6/site-packages/starlette/middleware/errors.py", line 103, in asgi
    await asgi(receive, _send)
  File "/Users/edwardbanner/.anaconda/lib/python3.6/site-packages/starlette/exceptions.py", line 74, in app
    raise exc from None
  File "/Users/edwardbanner/.anaconda/lib/python3.6/site-packages/starlette/exceptions.py", line 63, in app
    await instance(receive, sender)
  File "/Users/edwardbanner/.anaconda/lib/python3.6/site-packages/starlette/routing.py", line 43, in awaitable
    response = await run_in_threadpool(func, request)
  File "/Users/edwardbanner/.anaconda/lib/python3.6/site-packages/starlette/concurrency.py", line 24, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/Users/edwardbanner/.anaconda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/edwardbanner/.anaconda/lib/python3.6/site-packages/fastapi/applications.py", line 83, in <lambda>
    lambda req: JSONResponse(self.openapi()),
  File "/Users/edwardbanner/.anaconda/lib/python3.6/site-packages/fastapi/applications.py", line 75, in openapi                                                                                            
    openapi_prefix=self.openapi_prefix,
  File "/Users/edwardbanner/.anaconda/lib/python3.6/site-packages/fastapi/openapi/utils.py", line 248, in get_openapi                                                                                      
    flat_models=flat_models, model_name_map=model_name_map
  File "/Users/edwardbanner/.anaconda/lib/python3.6/site-packages/fastapi/utils.py", line 45, in get_model_definitions                                                                                     
    model_name = model_name_map[model]
KeyError: <class 'Body_compute'>
```

**Environment:**
 - OS: [e.g. macOS]
 - FastAPI Version [e.g. 0.27.0], get it with `pip install fastapi`.

```Python
import fastapi
print(fastapi.__version__)
```

**Additional context**

- When I only have a single endpoint, the value of `model_name_map` is `{<class 'Body_compute'>: 'Body_compute'}`.
- However, when I have both endpoints take multiple parameters, the value of `model_name_map` is `{<class 'Body_compute'>: 'None__Body_compute'}`.

**Comment by tiangolo** [comment]
Thanks for the report. I'll check it soon.

**Comment by tiangolo** [comment]
This is solved now by #347. :tada: 

It will be included in the next release.

**Comment by H1sx34** [comment]
@tiangolo still get same error in fastapi 0.105.0
```
@router.post("/test")
def test(q:str = Body(...), w: int = Body(...)):
    print(q, w)
    return AmisJsonModel(data={"q": q, "w": w})
```
fastapi/_compat.py:379 in get_model_definitions
