### ISSUE TITLE
TypeError: cannot create 'cython_function_or_method' instances

### ISSUE THREAD

**Issue by williamfzc** [tiangolo/fastapi#648]
**Describe the bug**

```python
tests/test_server.py:10: in <module>
    from j2db.server import Server
j2db/server.py:1: in <module>
    from fastapi import FastAPI
/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/fastapi/__init__.py:7: in <module>
    from .applications import FastAPI
/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/fastapi/applications.py:3: in <module>
    from fastapi import routing
/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/fastapi/routing.py:6: in <module>
    from fastapi import params
/opt/hostedtoolcache/Python/3.7.4/x64/lib/python3.7/site-packages/fastapi/params.py:14: in <module>
    class Param(Schema):
E   TypeError: cannot create 'cython_function_or_method' instances
```

**To Reproduce**

hmm ..  i don't know why. It suddenly happened in github actions and did not happen before.

**Environment:**

- Linux
- fastapi-0.42.0
- python 3.7.4

**Additional context**

**Comment by Toumetis** [comment]
pydantic 1.0.0 has been released, with breaking changes.
In particular, Field and Schema are now functions rather than classes & cannot be subclassed.

**Comment by MarcSaric** [comment]
Pinning to an older version of pydantic should temporarily fix this.

**Comment by williamfzc** [comment]
thanks :+1: waiting for a standard fix

**Comment by transhapHigsn** [comment]
Any update on when above PR will be merged?

**Comment by SKalt** [comment]
Looks like #646 has landed.

**Comment by tiangolo** [comment]
Thanks everyone for the discussion here!

Yes, this should be solved in the latest versions.

**Comment by lcsvcn** [comment]
Still happening for me:

My requirements.txt:
```
anyio==3.5.0
APIFlask==0.12.0
apispec==5.1.1
asgiref==3.5.0
attrs==21.4.0
certifi==2021.10.8
click==8.1.2
decorator==5.1.1
dependency-injector==4.39.1
fastapi==0.75.1
FastAPI-SQLAlchemy==0.2.1
Flask==2.1.1
Flask-HTTPAuth==4.5.0
flask-marshmallow==0.14.0
greenlet==1.1.2
h11==0.13.0
idna==3.3
importlib-metadata==4.11.3
iniconfig==1.1.1
itsdangerous==2.1.2
Jinja2==3.1.1
MarkupSafe==2.1.1
marshmallow==3.15.0
packaging==21.3
phonenumbers==8.12.46
pluggy==1.0.0
psycopg2-binary==2.9.3
py==1.11.0
pydantic==1.9.0
pyparsing==3.0.8
pytest==7.1.1
python-decouple==3.6
pytz==2022.1
sentry-sdk==1.5.8
six==1.16.0
sniffio==1.2.0
SQLAlchemy==1.4.35
starlette==0.17.1
tomli==2.0.1
typing_extensions==4.1.1
urllib3==1.26.9
uvicorn==0.17.6
validators==0.18.2
webargs==8.1.0
Werkzeug==2.1.1
zipp==3.8.0

```

My documentation:
![image](https://user-images.githubusercontent.com/6011385/162633989-21743311-6dfc-4f64-8b3b-8c6cf94a591e.png)
